### ISSUE TITLE
Responsiveness Issues

### ISSUE THREAD

**Issue by Kris0011** [ISF-DDU/ISF-website#11]
**Describe the bug**
Two text blocks are getting mixed in "Who we are?" and "What we do?" 

**To Reproduce**
When screen width is  small  around 1000px you can see the change in the layout which is not looking good .

**Expected behavior**
Layout should remain same for both PC and Mobile screens.

**Screenshots**
![image](https://github.com/ISF-DDU/ISF-website/assets/118788852/76aaf343-1a56-4a52-8627-20294e96f972)
![image](https://github.com/ISF-DDU/ISF-website/assets/118788852/44625a91-bc8d-46da-9c46-2d2a3e9fb521)

**Desktop (please complete the following information):**
 - OS: Linux 
 - Browser : Brave

**Comment by Kris0011** [comment]
If you find this issue useful i can work upon this .

**Comment by mihirh19** [comment]
@Kris0011 sure you can work on that issue
