### ISSUE TITLE
[New Feature, Hacktoberfest] Creating About Page

### ISSUE THREAD

**Issue by kevintamakuwala** [ISF-DDU/ISF-website#14]
Creating Responsive and Re-usable About page using React from scratch.

Assign this issue along with the required details for about page.

**Comment by vivekpanjwani** [comment]
can you assign me this task under hacktoberfest-accepted label

**Comment by mihirh19** [comment]
About iete 

The Institution of Electronics and Telecommunication Engineers(IETE)is India's leading recognised professional society devoted to advancment of science and technology of Electronics, Telecommunication & IT, Founded in 1953.

IETE NATIONAL BODY

The Institution of Electronics and Telecommunication Engineers (IETE) is Indias leading recognised professional society devoted to the advancement of Science and Technology of Electronics, Telecommunication & IT. Founded in 1953. The IETE is the National Apex Professional body of Electronics and Telecommunication, Computer Science and IT Professionals. It serves more than 1,25,000 members (including Corporate, Student and ISF members) through various 64 Centres, spread all over India and abroad.


OBJECTIVE OF IETE

The IETE focuses on advancement of the Science and Technology of Electronics, Telecommunication, Computers, Information Technology and related areas.

The Institution is known for providing leadership oppurtunities in Scientific and Technical areas of direct importance to the national development and economy.

The IETE conducts and sponsors technical meetings, conferences, symposia, and exhibitions all over India, publishes technical journals and provides continuing education as well as career advancement opportunities to its members.

**Comment by mihirh19** [comment]
@kevintamakuwala Go for it

**Comment by kevintamakuwala** [comment]
Can you provide me photographs to be included? @mihirh19

**Comment by mihirh19** [comment]
Team photos
