### ISSUE TITLE
UI: Better UI for the Homepage

### ISSUE THREAD

**Issue by dhruvdabhi101** [ISF-DDU/ISF-website#2]
**Is your feature request related to a problem? Please describe.**
Currently, Very basic front page, we can modify it a little bit and make it look more attractive. 

**Describe the solution you'd like**
Adding little bit of animations, and using appropriate Typography

**Describe alternatives you've considered**
No Alternatives ;)

**Additional context**
We will need colour palette and fonts. so we can make it look consistent over whole website.

**Comment by mihirh19** [comment]
Hacktoberfest is staring from tomorrow so we will be assign issue from tomorrow

**Comment by dhruvdabhi101** [comment]
Can you assign now ?

**Comment by mihirh19** [comment]
@dhruvdabhi101 assigned to you !
