### ISSUE TITLE
UI/UX Improvement in the Nav Bar 

### ISSUE THREAD

**Issue by AndrickSilva** [ISF-DDU/ISF-website#3]
**Is your feature request related to a problem? Please describe.**
I feel the Nav Bar looks a bit outdated and can be improved for a better user experience. 

**Describe the solution you'd like**
I would like to add a more modern-looking hover effect and also add active Links when the user is on a certain page which will help improve the user experience while navigating through different pages.

**Describe alternatives you've considered**
I can also improve the home page but considering Nav Bar as the first step in improving the website.

**Additional context**
![image](https://github.com/ISF-DDU/ISF-website/assets/94364805/6e6bf981-0feb-4a01-b791-069db0cd681c)
![image](https://github.com/ISF-DDU/ISF-website/assets/94364805/1eeeb341-b244-4e44-988a-67f0495a7a42)

**Comment by mihirh19** [comment]
Hacktoberfest is staring from tomorrow so we will be assign issue from tomorrow

**Comment by AndrickSilva** [comment]
Ok, Sure 
Thanks

**Comment by AndrickSilva** [comment]
Hi @mihirh19, 
Can I create PR for the above?

**Comment by mihirh19** [comment]
@AndrickSilva assigned to you

**Comment by AndrickSilva** [comment]
Hi @mihirh19, The Task is Completed please review and merge the PR
