### ISSUE TITLE
Responsive Navbar 

### ISSUE THREAD

**Issue by AndrickSilva** [ISF-DDU/ISF-website#5]
**Is your feature request related to a problem? Please describe.**
If it's okay with you I can make the Navbar responsive too.
Looks like you are adding another Navbar for responsive design but I feel we can reuse the desktop navbar only and make it responsive. This will help to increase the speed and reduce the load time.

**Describe the solution you'd like**
Mentioned Above

**Describe alternatives you've considered**
Mentioned Above

**Additional context**

**Comment by theavitw** [comment]
Sure, 
@AndrickSilva  
I got it.
I will do this.
Kindly assign me

**Comment by mihirh19** [comment]
@theavitw assigned to you !

**Comment by AndrickSilva** [comment]
All the best, 
Happy contributing

**Comment by theavitw** [comment]
Hey , 
Why you close this issue?

**Comment by Kris0011** [comment]
I can work on this !
