### ISSUE TITLE
Hamburger navbar under page content

### ISSUE THREAD

**Issue by HarjjotSinghh** [ISF-DDU/ISF-website#6]
# **Description of bug**
- Hamburger navbar open by default in mobile view. 
- Hamburger navbar overflowing in mobile view

# **To Reproduce**
1. Add media queries
2. Add additional JavaScript for correct behavior.

# **Expected behavior**
- Hamburger navbar closed by default.
- Hamburger navbar displaying on top of all other content.

# **Screenshots**
![Screenshot 2023-10-01 144209](https://github.com/ISF-DDU/ISF-website/assets/114088280/da6bea6e-e521-40f5-b05f-56cdf3c75f42)

# **Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version Latest

# **Smartphone (please complete the following information):**
 - Device: iPhone XR
 - OS: iOS
 - Browser Safari
 - Version 22

**Comment by theavitw** [comment]
I will do it

**Comment by mihirh19** [comment]
Ok @theavitw i will assign to you

**Comment by theavitw** [comment]
hey @mihirh19  
Can I use react-bootstrap and bootstrap??

**Comment by mihirh19** [comment]
No @theavitw you can use flowbite and tailwind
