### ISSUE TITLE
can i create the contact page

### ISSUE THREAD

**Issue by Kunal-deve1oper** [ISF-DDU/ISF-website#8]
I noticed that there is no content on the contact page. Would you like me to create the contact page for you?

**Comment by mihirh19** [comment]
@Kunal-deve1oper yes , you can create contact page

**Comment by Kunal-deve1oper** [comment]
OK i am working on it

**Comment by mihirh19** [comment]
@Kunal-deve1oper assigned!!

happy contributing🚀

**Comment by Kunal-deve1oper** [comment]
can you provide the address and some social links?

**Comment by mihirh19** [comment]
Address : nadiad , Gujarat 

[Instagram](https://instagram.com/the_techtribe?igshid=OGQ5ZDc2ODk2ZA==) 

[LinkedIn ](https://www.linkedin.com/company/tech-tribe-the-community/)

**Comment by mihirh19** [comment]
For more you can view README file

**Comment by Kunal-deve1oper** [comment]
Any official mail?

**Comment by mihirh19** [comment]
Sorry , we don’t have at present 
But you can use this email 

techtribeddu@gmail.com

**Comment by Kunal-deve1oper** [comment]
ok thanks
